version: "3.8"
services:
    mysql:
        container_name: sad_mysql
        restart: unless-stopped
        image: mysql:latest
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: "admin"
            MYSQL_USER: "admin"
            MYSQL_PASS: "test"
        volumes:
            - ./data-volume:/var/lib/mysql
            - ./data-source:/data

volumes:
    data-volume:
    data-source:
