CREATE DATABASE DWH;
USE DWH;

CREATE TABLE DWH.D_CUSTOMERS
(
    CUSTOMER_KEY BIGINT NOT NULL AUTO_INCREMENT,
    CUSTOMER_UNIQUE_ID VARCHAR(50) NOT NULL,
    CUSTOMER_ZIPCODE VARCHAR(5) NOT NULL,
    CUSTOMER_CITY VARCHAR(50) NOT NULL,
    CUSTOMER_STATE VARCHAR(50) NOT NULL,
    CUSTOMER_GEO_LAT DOUBLE PRECISION NOT NULL,
    CUSTOMER_GEO_LONG DOUBLE PRECISION NOT NULL,
    CUSTOMER_DATE_FROM TIMESTAMP,
    CUSTOMER_DATE_TO TIMESTAMP,
    CONSTRAINT D_CUSTOMERS_PK PRIMARY KEY (CUSTOMER_KEY)
);

CREATE TABLE DWH.D_ORDER_PAYMENTS
(
    PAYMENT_KEY BIGINT NOT NULL AUTO_INCREMENT,
    ORDER_ID VARCHAR(50) NOT NULL,
    PAYMENT_SEQUENTIAL SMALLINT NOT NULL,
    PAYMENT_TYPE VARCHAR(20) NOT NULL,
    PAYMENT_INSTALLMENTS SMALLINT NOT NULL,
    PAYMENT_VALUE REAL NOT NULL,
    PAYMENTS_DATE_FROM TIMESTAMP,
    PAYMENTS_DATE_TO TIMESTAMP,
    CONSTRAINT D_ORDER_PAYMENTS_PK PRIMARY KEY (PAYMENT_KEY)
);

CREATE TABLE DWH.D_PRODUCTS
(
    PRODUCT_KEY BIGINT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID VARCHAR(50) NOT NULL,
    PRODUCT_CATEGORY_NAME VARCHAR(100) NOT NULL,
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(100) NOT NULL,
    PRODUCT_NAME_LENGHT SMALLINT NOT NULL,
    DESCRIPTION_LENGHT INTEGER NOT NULL,
    PRODUCT_PHOTO_QTA SMALLINT NOT NULL,
    PRODUCT_WEIGHT_GRAMS SMALLINT NOT NULL,
    PRODUCT_LENGHT_CM SMALLINT NOT NULL,
    PRODUCT_HEIGHT_CM SMALLINT NOT NULL,
    PRODUCT_WIDTH_CM SMALLINT NOT NULL,
    PRODUCT_DATE_FROM TIMESTAMP,
    PRODUCT_DATE_TO TIMESTAMP,
    CONSTRAINT D_PRODUCTS_PK PRIMARY KEY (PRODUCT_KEY)
);

CREATE TABLE DWH.D_SELLERS
(
    SELLER_KEY BIGINT NOT NULL AUTO_INCREMENT,
    SELLER_ID VARCHAR(50) NOT NULL,
    SELLER_ZIPCODE VARCHAR(5) NOT NULL,
    SELLER_CITY VARCHAR(50) NOT NULL,
    SELLER_STATE VARCHAR(50) NOT NULL,
    SELLER_GEO_LAT DOUBLE PRECISION NOT NULL,
    SELLER_GEO_LONG DOUBLE PRECISION NOT NULL,
    SELLER_DATE_FROM TIMESTAMP,
    SELLER_DATE_TO TIMESTAMP,
    CONSTRAINT D_SELLERS_PK PRIMARY KEY (SELLER_KEY)
);

CREATE TABLE DWH.F_ORDERS
(
    ORDER_ID VARCHAR(50) NOT NULL,
    CUSTOMER_KEY BIGINT NOT NULL,
    PRODUCT_KEY BIGINT NOT NULL,
    SELLER_KEY BIGINT NOT NULL,
    PAYMENT_KEY BIGINT NOT NULL,
    ORDER_ITEM_QTA SMALLINT NOT NULL,
    PRICE REAL NOT NULL,
    FREIGHT_VALUE REAL NOT NULL,
    ORDER_STATUS VARCHAR(30) NOT NULL,
    REVIEW_SCORE SMALLINT NOT NULL,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP NOT NULL,
    ORDER_APPROVAL_TIMESTAMP TIMESTAMP NOT NULL,
    ORDER_DELIVERED_CARRIER_TIMESTAMP TIMESTAMP NOT NULL,
    ORDER_DELIVERED_CUSTOMER_TIMESTAMP TIMESTAMP NOT NULL,
    ORDER_ESTIMATED_DELIVERY_TIMESTAMP TIMESTAMP NOT NULL
);

ALTER TABLE DWH.F_ORDERS
ADD CONSTRAINT F_ORDERS_D_CUSTOMERS_FK FOREIGN KEY (CUSTOMER_KEY)
REFERENCES DWH.D_CUSTOMERS (CUSTOMER_KEY)
MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE DWH.F_ORDERS
ADD CONSTRAINT F_ORDERS_D_ORDER_PAYMENTS_FK FOREIGN KEY (PAYMENT_KEY)
REFERENCES DWH.D_ORDER_PAYMENTS (PAYMENT_KEY)
MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION;


ALTER TABLE DWH.F_ORDERS
ADD CONSTRAINT F_ORDERS_D_PRODUCTS_FK FOREIGN KEY (PRODUCT_KEY)
REFERENCES DWH.D_PRODUCTS (PRODUCT_KEY)
MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION;

ALTER TABLE DWH.F_ORDERS
ADD CONSTRAINT F_ORDERS_D_SELLERS_FK FOREIGN KEY (SELLER_KEY)
REFERENCES DWH.D_SELLERS (SELLER_KEY)
MATCH SIMPLE
ON UPDATE NO ACTION
ON DELETE NO ACTION;

CREATE INDEX FKI_F_ORDERS_D_CUSTOMERS_FK
ON DWH.F_ORDERS(CUSTOMER_KEY);

CREATE INDEX FKI_F_ORDERS_D_ORDER_PAYMENTS_FK
ON DWH.F_ORDERS(PAYMENT_KEY);

CREATE INDEX FKI_F_ORDERS_D_PRODUCTS_FK
ON DWH.F_ORDERS(PRODUCT_KEY);

CREATE INDEX FKI_F_ORDERS_D_SELLERS_FK
ON DWH.F_ORDERS(SELLER_KEY);
