-- Staging
CREATE DATABASE STAGING;
USE STAGING;

CREATE TABLE STAGING.STAGING_CUSTOMERS
(    
    CUSTOMER_UNIQUE_ID VARCHAR(50), 
    CUSTOMER_ZIPCODE VARCHAR(5), 
    CUSTOMER_CITY VARCHAR(50), 
    CUSTOMER_STATE VARCHAR(50),
    CUSTOMER_GEO_LAT DOUBLE PRECISION, 
    CUSTOMER_GEO_LONG DOUBLE PRECISION
);

CREATE TABLE STAGING.STAGING_ORDER_PAYMENTS
(    
    ORDER_ID VARCHAR(50), 
    PAYMENT_SEQUENTIAL INTEGER, 
    PAYMENT_TYPE VARCHAR(20),
    PAYMENT_INSTALLMENTS INTEGER,
    PAYMENT_VALUE REAL
);

CREATE TABLE STAGING.STAGING_ORDERS
(    
    ORDER_ID VARCHAR(50),
    CUSTOMER_UNIQUE_ID VARCHAR(50), 
    PRODUCT_ID VARCHAR(50),
    SELLER_ID VARCHAR(50),
    ORDER_ITEM_QTY INTEGER, 
    PRICE REAL,
    FREIGHT_VALUE REAL,
    ORDER_STATUS VARCHAR(30),
    REVIEW_SCORE INTEGER, 
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
    ORDER_APPROVAL_TIMESTAMP TIMESTAMP,
    ORDER_DELIVERED_CARRIER_TIMESTAMP TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_TIMESTAMP TIMESTAMP,
    ORDER_ESTIMATED_DELIVERY_TIMESTAMP TIMESTAMP
);

CREATE TABLE STAGING.STAGING_PRODUCTS
(    
    PRODUCT_ID VARCHAR(50),
    PRODUCT_CATEGORY_NAME VARCHAR(100), 
    PRODUCT_CATEGORY_NAME_ENGLISH VARCHAR(100),
    PRODUCT_NAME_LENGTH INTEGER,
    PRODUCT_DESCRIPTION_LENGTH INTEGER,
    PRODUCT_PHOTO_QTY INTEGER,
    PRODUCT_WEIGHT_GRAMS INTEGER,
    PRODUCT_LENGTH_CM INTEGER,
    PRODUCT_HEIGHT_CM INTEGER,
    PRODUCT_WIDTH_CM INTEGER
);

CREATE TABLE STAGING.STAGING_SELLERS
(
    SELLER_ID VARCHAR(50),
    SELLER_ZIPCODE VARCHAR(5),
    SELLER_CITY VARCHAR(50), 
    SELLER_STATE VARCHAR(50),
    SELLER_GEO_LAT DOUBLE PRECISION, 
    SELLER_GEO_LONG DOUBLE PRECISION
);
